Fix warnings
This commit resolves more than 200 warnings.  It explicitly avoids doing
any refactoring that changes the semantics of the code.  All refactoring
that should be cleaned up in subsequent commits can be found by
searching for string `TODO WALL`.

* Many non-exhaustive pattern matches are now handled using
  `error "TODO WALL: NON-EXHAUSTIVE PATTERN MATCH"`.  Note that `error`
  is used even in monadic contexts, for consistency.
* Redundant pattern matches are commented out and annotated with
  `-- TODO WALL: REDUNDANT PATTERN MATCH` comments.
* Dead code is commented out using block comments and annotated with
  `TODO WALL: DEAD CODE`.

This commit only fixes warnings in modules that are being built.  I
tested using the following flags:

* Defaults
* `-f+debug`
* `-f+debug -f+tracy`
    * Haskell modules build, but the C++ fails to build on my system.
* `-f+bounds-checks`
* `-f+memory-counter`
* `-f+internal-checks`
* `-f+nofib`

I tested with GHC 9.4.8 using the current version of Cabal (3.18.1.0).
I also tested using the current version of Stack (3.11.1), using the
existing `stack.yaml`, which uses `lts-21.25` and the same GHC version.
We should address the range of supported GHC versions in a later commit.
My understanding is that we will make GHC 9.4 (or perhaps even a later
version) the lower bound.

Some warnings remain in vendored C code.  For example,
`Data.Array.Accelerate.Debug.Internal.Flags` uses vendored C source
`cbits/getopt_long.c`.  The C compiler issues a warning, which GHC
displays as an error even though it does not treat it as an error.

```
cbits/getopt_long.c: In function ‘getopt_internal’:

cbits/getopt_long.c:529:18: error:
     warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
      529 |             (oli = strchr(options, optchar)) == NULL) {
          |                  ^
    |
529 |             (oli = strchr(options, optchar)) == NULL) {
    |                  ^
```

This example is system-dependent.  The `getopt` library is vendored,
but it uses standard headers that are not vendored.  This warning is
emitted on my system because my `libc` defines `strchar` with a `const`
return value.  It could be resolved using an explicit cast:
`(oli = (char*) strchr(options, optchar)) == NULL)`.  This is vendored
code, however, so we may not want to fix (patch) the issue in that
source.

I experimented with updating the vendored code to the latest version,
just to see if it resolves the issue or not, and I confirmed that it
does *not* resolve the issue.

<https://github.com/openbsd/src/blob/master/include/getopt.h>
<https://github.com/openbsd/src/blob/master/lib/libc/stdlib/getopt_long.c>